[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
In this part we talk about the communication in two contexts, one is business context where we specifies 
communication partners with explanations of the domain and some schemes and the other one is the technical 
context where we do the same in a technical context.
****


=== Business Context

[role="arc42help"]
****
In this part we use an scheme to specify the communications of the person who is using the application with the application. First of all he 
logins with Solid, then when he is inside the appication we have to commuicate with the pods to store or see routes, if we want to 
send any route we have to communicate with the other pods of the users.
****


=== Technical Context

[role="arc42help"]
****
In this part we have to specify the same we had in previous point but with a technical view.
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
