[[section-concepts]]
== Cross-cutting Concepts

This section describes overall, principal regulations and solution ideas that are relevant in multiple parts of the system.

=== Domain Model

Overview of the fundamental data structures of the system and their relevant relationships.

...

=== User Experience

==== User Interface

The user interface is developed with React. Screenshots of the main pages are shown below.

==== Internationalization

This app will be available in English.

=== Security and Safety

==== Security

The application security is provided by the Solid Authentication Client and the Solid POD.

==== Safety

No part of the system has an aspect that endangers the life of the user.

=== “Under-the-hood”

==== Persistency

The application is based on a decentralized system. Therefore, all information will be stored in each user's personal POD. It will be the user who grants the read / write permissions.

==== Transaction Handling

The transactions realized across the application are asynchronous.

==== Session Handling

Session is handled by Solid Authentication Client.

==== Exception/Error Handling

...